### PR TITLE
merging the ImageDomainCorrector into main code and adding tests

### PR DESCRIPTION
**Pull request by bwheelz36**
@paulzyliu Hey, I should have looked at this more closely before I merged it, turns out your code was in a module called MRI_DistortionQA and the rest of the code was in the renamed module (mri_distortion_toolkit) - so even though all the checks passed it turns out your code wasn't actually being checked!

- In this commit I merged it all back together and tidied up the inheritance a bit:
  - if you don't need to change the __init__ behavior (as in the ImageDomainDistortionCorrector), you don't need to write a new method
  - if you want to add new parameters (as in the KspaceDistortionCorrector), the cleanest way is to use something like this:
      ```python
      class NewClass(BaseClass):
          def __init__(some_new_parameter=10, **kwds)
              super.__init__(**kwds)    
      ```
  In this way any other parameters you pass go into a dictionary called kwds, which will be passed to the base class. If kwds is missing some required field (in our case ImageDirectory for instance) you will get an error the same way you would if you tried to instantiate the a class without passing required arguments.
  - I removed the default _correct_image from DistortionCorrectorBaseClass, and made it an abstract method:
    ```python
    @abstractmethod
    def _correct_image(self):
        pass
    ```

  this means any inheriting classes are required to supply their own version of this method

- I added a test of the ImageDomainCorrrection - it's just a test that it runs at this point - we could (probably should) also add some accuracy tests on the test data

### CODE REVIEW

**Comment by paulzyliu** [comment]
nice! looks a lot better now.. I might just do a fresh clone, not sure what's happening with the project name

I was playing around with the **kwds before and the issue I was having was that when you then instance the class, pycharm wasn't autofilling/suggesting the parameter names anymore (from the base class)? was I doing it wrong?

**Comment by bwheelz36** [comment]
> "was I doing it wrong?"

No - Pycharm probably isn't that smart :-(

**Comment by paulzyliu** [comment]
There's also now a "pl" folder in the examples folder that I wasn't suppose to commit, you can delete it from the main branch

**Comment by bwheelz36** [comment]
no worries, if you add 'temp' anywhere in a file/folder name then it should be automatically ignored :-)

**Pull request merged**
